
import java.util.Scanner;

/*
 * This is the FightingMatch class. In this class, the two Players: The Hero
 * and the Villain will go against one another. 
 */
public class FightingMatch {

	private static Player goFirst; //represents Player that will go first
	private static Player goSecond; //represents Player that will go second
	private static Scanner scanner = new Scanner (System.in); //Scanner
	//to retrieve input from user


	// Private Helper Methods
	
	/*
	 * goFirst(Player, Player) determines which Player will go first. The
	 * Player with the lower strength will go first, but if the strengths
	 * are the same, then the Hero will go first.
	 */
	private static void goFirst(Player hero, Player villain) {
		goFirst = hero.getStrength() <= villain.getStrength() ? hero : villain;
		goSecond = hero.getStrength() > villain.getStrength() ? hero : villain;
		System.out.println("\nFor this match, " + goFirst.getName() + " will go"
				+ " first, and " + goSecond.getName() + " will go second!");

	}
	
	/*
	 * playerTurn(Player, Player) shows what happens for each Player's turn.
	 * First, the current Player will be asked to guess a number between 1 to 3.
	 * If the current Player's guess matches the random number generated by the
	 * program, then the current Player can either 1) land a punch or 2) perform
	 * their special move (if they have any remaining). If the current Player
	 * incorrectly guesses, then the opposing Player will go next.
	 */
	private static void playerTurn(Player curr, Player opponent) {
		System.out.println("\n" + curr.getName() + "'s turn. "
				+ "A random number between 1 and 3 (included) will now "
				+ "generated.\nIf you guess correctly, "
				+ "you can throw a punch or use your special move!\nIf you do"
				+ " not guess correctly, well, wait for your next turn");
		
		//Program will generate a random number between 1-3;
		
		int randomNum = (int)(Math.random()*3)+1;
		System.out.println("\nThe random number has been made. Guess what "
				+ "it is!");
		int playerGuess = scanner.nextInt();
		
		//Correct Guess
		if(playerGuess == randomNum) {
			System.out.println("\nCorrect Guess! Now, you have the ability"
					+ "  to throw a punch or do your special move.\nPlease"
					+ " type p if you wish to throw a punch, or s to use your "
					+ "specialMove.\n NOTE: If you have no more special moves,"
					+ " then by default, you will throw a punch.");
			
			System.out.println("Enter your choice:");
			Scanner scannerChoice = new Scanner(System.in);
			String playerChoice = scannerChoice.nextLine();
			
			//Based on the choice, the following will be done:
			
			//Player enters 'p' or if they are out of special moves, then
			//they will just punch their opponent
			
			if(playerChoice.equals("p") || curr.getNumSpecialMoves() < 1) {
				curr.punch(opponent);
			}
			
			//else, if the Player has entered 'q' and they have special moves
			//left, they can use their special move
			
			else {
				curr.specialMove();
			}

		}
		
		//Incorrect Guess
		else {
			System.out.println("Wrong guess! Good luck next time!");
		}
	}
	
	private static void runGame(Player first, Player second) {
		
		while(first.getHealth() > 0 && second.getHealth() > 0) {
			
			playerTurn(first, second);
			playerTurn(second, first);
			
		}
		
		//Once the game ends.
		System.out.println("\nGAME OVER!");
		String result = first.getHealth() > second.getHealth() ? 
				"\n" + first.getName() + " won the game!"
				+ "Congrats": "\n" + first.getName() + " won the game!"
				+ "Congrats";
		System.out.println("\n" + result);
		scanner.close(); //close scanner
	}

	public static void main(String[] args) {

		// Receive input from the players of the Game, and print out
		// the input

		System.out.println("Player 1 is the Hero. Hero, " + 
		"please enter your name!");
		String heroName = scanner.nextLine();

		// Create a new Hero based on the input data. Note that the strength
		// will be calculated randomly, but will range from 200-250.

		Player hero = new Hero(heroName, (int) (Math.random() * 51) + 200);
		System.out.println(hero); // Print out the Hero's name and strength

		// Enter input data for the Villain. Create a new Villain instance
		//based on the input data.
		
		System.out.println("Player 2 is the Villain. Villain, " + 
		"please enter your name!");
		String villainName = scanner.nextLine();
		Player villain = new Villain(villainName, (int)
				(Math.random() * 51) + 200);
		System.out.println(villain);
		System.out.println("Now that we have the two players, lets decide"
				+ " who will go first.\nThe player with the lowest strength"
				+ " will go first.\nIf the players have the same strength, then"
				+ " the Hero will go first!");
		
		// The player with the lowest strength will go first. If the
		// strengths are the same, then the Hero will go first. This
		//will be determined by invoking the goFirst() private helper method
		
		goFirst(hero, villain);
		
		//invoke the runGame() method to start the match.
		System.out.println("LET THE MATCH BEGIN!");
		runGame(goFirst, goSecond);
		

	}

}
